import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar";
import Settings from "@/components/settings";
import Navbar from "@/components/navbar";
import Category from "@/components/category";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="h-screen py-[3vh] px-[3vh] gap-[30px] flex justify-between">
            <SideBar />
            <div className="w-full h-full flex flex-col">
              <Navbar />
              <div className="flex gap-[30px] h-full w-full">
                <div className="w-4/5 flex gap-[33px]">
                  <div>
                    <Category />
                  </div>
                  {children}
                </div>
                <div className="w-1/5">
                  <Settings />
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
